### PR TITLE
2022 registration open

### LINKED ISSUE #102: Update Marketing Site to Reflect Program Announcement & Registration Opening
## Description of Task

We would like to announce our program of talks selected from the CFP and announce the opening of registration on April 26 around 9:30 AM PT. As such, we need some changes made to the marketing site to reflect new information and calls-to-action. Here is a rundown of the requests, which I'll go into more detail on below:

- Update "Attend" Section + Menu Option 
- Add Registration Button to Hero Section
- Edit  "Talk Info" Section + Menu Option
- Edit Site Banner Notification

## Granular Copy + Design Requests

_Note: [Here](https://docs.google.com/presentation/d/1TwG2EJCgsof9hfiuBBhUj4IGxlAaMGecJtL4D0hYHfE/edit?usp=sharing) is a slideshow containing visual edits for each section described below._ 

### Update "Attend" Section + Menu Option

- [x] Emphasize **Attend** Menu Option in some way to make it stand out. Example [here](). 
- [x] Make the following copy change to **Registration** subsection: `~~Return here on April 26, 2022 to grab your ticket!~~ Click [here](l[ink TBD](https://ti.to/codenewbie/codeland-2022)) to register for CodeLand 2022!` — This copy should be a bit larger and bolder than the text that we'll be replacing

### Add Registration Button to Hero Section

- [x] Add a button to hero section (underneath copy that reads: `Taking place virtually on June 16 & 17, 2022`). Button should say `Register` and link to [this](https://ti.to/codenewbie/codeland-2022) webpage _(note: waiting on this page to be set up but I'll add it back here by EOD Monday)_. 
- [x] De-emphasize copy that reads `Taking place virtually on. June 16 & 17, 2022.` to make button below it stand out more. 

### Edit  "Talk Info" Section + Menu Option

- [x] Change title of `Talk Info` menu option + section to `Program`
- [x] Add subheading underneath existing `The magic of CodeLand [...]` copy that reads: `Keynotes` (we kind of already have this with the keynote announcement section. A propoosed change is in the slideshow linked above).
- [x] In this section, include circle-framed headshot of Angie Jones, left-justified with bold text that reads `Angie Jones` (We already have this set up.)
- [x] To the right of Angie's headshot + name, add the following copy: `Angie Jones is the Global V.P. of Developer Relations at Block, an IBM Master Inventor as well as an award-winning teacher and a supportive figure for early-career software developers.`
- [x] After Angie's bio, add the existing `Learn More` button. 

- [x] Underneath the Angie section, add [this](https://user-images.githubusercontent.com/69541346/164790748-56489eb5-06f6-452d-a7dd-6b353bae8971.png)
blurry graphic, also in a circle-frame, also left-justified with bold text next to it that reads `Keynote to be announced.`

- [x] Again, underneath, add [this](https://user-images.githubusercontent.com/69541346/164790968-eabb0cdf-d464-4fae-b59c-f01eca3dc9fd.png) blurry graphic, also in a circle-frame, also left-justified with bold text next to it that reads `Keynote to be announced.`

- [x] Add a subtle dividing line/color block change

- [x] Add another subheading that reads `Talks` (same size/style as `Keynotes` subheading)
- [x] Add list of our pre-recorded speakers' names and talk titles, grouped by talk theme and then listed alphabetically by first name within that grouping. Names should be left-justified and in a slightly larger/bolded font. Talk Titles should be in smaller, italicized, non-bolded font to the right. Talk. themes should each have a dedicated color and be attached to the far right of each row. 

**_[>>Speaker Names, Talk Titles, and Themes located in this pre-ordered sheet](https://docs.google.com/spreadsheets/d/1N5ALRMcv0uuX3TkhiBOXTZh3RmdiQZNdZDOuwE08A_U/edit?usp=sharing)_**

- [x] Delete the following copy: `The CodeLand Call-For-Proposals closed on March 29, 2022. Our Program Committee is currently reviewing submissions and we'll be announcing selections in the coming weeks. If you submitted a talk, please monitor your email for communications from our team about the status of your proposal.`
- [x] Add another registration button below the program content. Again, link should go here: https://ti.to/codenewbie/codeland-2022

### Edit Site Banner Notification

- [x] Delete our existing Angie Jones notification site banner and replace with the following notification copy: `Registration for CodeLand 2022 is now open and our program is live. Learn more [here](link)!` (note: link yet to be available. will add asap)

## Deadlines or Timeline

Before 11:30 AM ET on Tuesday, April 26, 2022. 

Please note that we are still waiting on a few speaker confirmations so some of the content in that section is subject to change

Thanks!

### PR DESCRIPTION
**Pull request by danieltott**
- closes #102

A couple notes:

- I adjusted some of the copy to remove "click here" type links ([reference](https://granicus.com/blog/why-click-here-links-are-bad/)) - feel free to adjust etc
- I took the talks data from the linked spreadsheet, but there are some incomplete titles. I think Abby was going to update the json for that - that can be done directly in here if possible!
- The design is the same as last year. Since there are no abstracts for talks nor bios for speakers, it looks a little bit sparse. Let me know if you'd like me to try to change anything up there.
- The Themes I randomly chose colors from last year

### CODE REVIEW

**Comment by danieltott** [comment]
@abbyphoenix if you'd like to update the talk data - you can do that directly right here: https://github.com/code-newbies/codeland/blob/danieltott/2022-registration-open/data/talks2022.json

**Comment by danieltott** [comment]
@abbyphoenix I replaced the `null` ones with "None" for right now so the preview is working again!

**Comment by SGGregory** [comment]
Not sure if this is the best way to propose copyedits or not, but for the sake of time, I'll leave my edits here. Feel free to redirect me to the proper way to do this!

- We should actually remove "Now" from the registration button text (in all three spots) so they instead read `Register for CodeLand 2022`
- @abbyphoenix this isn't something we've discussed, but some of the bios are written in the first person and some are in 3rd. I'll want to change this if possible so I'll sidebar with you about the possibilities

**Comment by abbyphoenix** [comment]
Re: the program json, a status update from me. We're waiting on two changes to the program:

- The last accepted speaker to confirm. I just emailed him to try to move things along.
- @SGGregory to update some of the bios to ensure they're all in third-person

For now though, program looks good to me!

**Review by abbyphoenix — CHANGES_REQUESTED** [review]
- I see that we opted for two blurred-out photos for the keynoters-to-come. They both look like blurred out pics of Tracy.  @sggregory Can we confirm if we would prefer to have a blurred-out photo of Kelsey to use for the middle one? I've asked him for his materials but gave him a deadline of the end of this week. But if it's just a blurred pic, I think it's fine to grab a pic from the internet. 
- [x] In the top nav, the order goes Attend, Program, Sponsorship. But on the site itself, it's Attend, Sponsorship, Program. @danieltott, can we move the Sponsorship section below Program on the page itself?

**Comment by SGGregory** [comment]
> * I see that we opted for two blurred-out photos for the keynoters-to-come. They both look like blurred out pics of Tracy.  @SGGregory Can we confirm if we would prefer to have a blurred-out photo of Kelsey to use for the middle one? I've asked him for his materials but gave him a deadline of the end of this week. But if it's just a blurred pic, I think it's fine to grab a pic from the internet.
> * [x]  In the top nav, the order goes Attend, Program, Sponsorship. But on the site itself, it's Attend, Sponsorship, Program. @danieltott, can we move the Sponsorship section below Program on the page itself?

@abbyphoenix thanks for pointing this out! I meant to leave this comment as well. We should have a blurred-out photo of Kelsey instead of two of Tracy. That file is [here](https://user-images.githubusercontent.com/69541346/164790968-eabb0cdf-d464-4fae-b59c-f01eca3dc9fd.png)

**Comment by SGGregory** [comment]
> Re: the program json, a status update from me. We're waiting on two changes to the program:
> 
> * The last accepted speaker to confirm. I just emailed him to try to move things along.
> * @SGGregory to update some of the bios to ensure they're all in third-person
> 
> For now though, program looks good to me!

Bios are updated on CFP App!

**Comment by danieltott** [comment]
@SGGregory @abbyphoenix Got all of these fixes pushed up!

**Review by abbyphoenix — COMMENTED** [review]
Awesome! So @danieltott -- my understanding is that, at least from my perspective, this is good to go in terms of what we need from you. I still need to either update with a new .json once this last person confirms _or_ confirm that we're proceeding without them if we don't hear from them. But all of that should be something I can do via the .json file upload (or not), I don't think I have any other changes that I need you to make to the page itself -- what about you, @SGGregory?

**Comment by SGGregory** [comment]
@abbyphoenix  All good on my end! The only thing is that we'll have a live announcement post to link to tomorrow in the site notification banner area. I'm expecting that to be live at 9:30 AM PT if not at 9:00 AM PT. I'll share it here in the comments tomorrow when it's live and that can also be the signal to make the all changes live?  @danieltott. 

Great work.

**Pull request merged**
