### PR TITLE
Update site with 2021 conference program

### LINKED ISSUE #66: Update site with 2021 conference program
In advance of registration opening next Tuesday (8/17), there are some changes that need to be made on codelandconf.com:

- The CFP/"Submit a Talk" section should be replaced with the 2021 conference program. [I've already swapped in the 2020 program here,](https://github.com/code-newbies/codeland/pull/65) the data just needs to be updated (either by manually copy pasting it or by updating the `.yml` files in the repo). Abby can export the data from this year's CFP (I think in `.json`).
- The current program layout needs to be redesigned a little:
  - The headers that previously distinguished talks/workshops by day (eg: "Talks - Thursday, July 23") should instead indicate the track theme a talk falls under (eg: "Early Career Confidence") 
  - Keynote speakers should be visually distinct from the other scheduled talks; I think we'll plan to keep the speaker photos only for the keynotes
  - The remaining talks should have title, name, and bio only (no photo or talk abstract), for example:

> EARLY-CAREER CONFIDENCE
>
> The Cost of Data
> Vaidehi Joshi
> Vaidehi Joshi is…
> 
> Machine Learning on the Edge
> Sangeetha KP
> A Software Developer, an Author and a Speaker…

- The registration section under "Attend" should just be updated with a call to action/link to registration (still waiting on this).

I can help with styling and rearranging the template, but don't have the experience to work with the YAML files, image sizing, or resolving a11y issues in this section. Let me know!

### PR DESCRIPTION
**Pull request by emmmmmmmmmmmma**

### CODE REVIEW

**Comment by danieltott** [comment]
@emmmmmmmmmmmma OK this is updated with live data etc. You'll see I hard-coded the keynote speakers section like we talked about (I just repeated the first block a few times to get the idea), and then I added tracks and talks below. 

The markup for these sections is not my favorite - it was mostly to get the data stuff going, so no worries to change anything I did here, I just wanted to get the live data going for you 👍 

Hit me up with any questions!

**Comment by SGGregory** [comment]
Heads up — it looks like there are some spacing issues (via the JSON dataset) on mobile. Screenshots attached. 
IMG_5774

IMG_5775

**Comment by SGGregory** [comment]
Also, I think we can now remove the `Important Dates` section altogether now that the CFP has closed. Let me know if you'd like me to add suggestions like this elsewhere @danieltott

**Comment by nickytonline** [comment]
@danieltott, once @SGGregory and Abby sign off on this, feel free to merge.

**Pull request merged**
